[package]
name = "zc_plot"
version = "0.1.0"
edition = "2021"

[dependencies]
charming = { version = "0.3.1", features = ["ssr"] }
clap = { version = "4.5.17", features = ["derive"] }
csv = "1.3.0"
regex = "1.10.6"
